# Generated by Django 4.1.6 on 2023-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
    ]
