# Generated by Django 4.1.6 on 2023-02-13 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipelist",
            old_name="recipe",
            new_name="recipes",
        ),
        migrations.RenameField(
            model_name="recipelist",
            old_name="url_link",
            new_name="url_links",
        ),
    ]
