# Generated by Django 4.1.6 on 2023-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0002_rename_recipe_recipelist_recipes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipelist",
            name="recipes",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="recipelist",
            name="url_links",
            field=models.URLField(unique=True),
        ),
    ]
