# Generated by Django 4.1.6 on 2023-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0004_remove_recipelist_id_alter_recipelist_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipelist",
            name="images",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
