# Generated by Django 4.1.6 on 2023-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food_planner", "0007_delete_recipelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeList",
            fields=[
                (
                    "recipes",
                    models.CharField(
                        max_length=250, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("url_links", models.URLField(unique=True)),
                ("images", models.ImageField(upload_to="")),
            ],
        ),
    ]
