# Generated by Django 4.1.6 on 2023-02-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0008_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipelist",
            name="images",
            field=models.URLField(unique=True, verbose_name=250),
        ),
    ]
