# Generated by Django 4.1.6 on 2023-02-18 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0010_alter_recipelist_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipelist",
            name="images",
        ),
    ]
