# Generated by Django 4.1.6 on 2023-02-18 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0011_remove_recipelist_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipelist",
            old_name="url_links",
            new_name="urls",
        ),
    ]
