# Generated by Django 4.1.6 on 2023-02-18 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0012_rename_url_links_recipelist_urls"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeList",
        ),
    ]
