# Generated by Django 4.1.6 on 2023-02-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0018_alter_recipelist_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipelist",
            name="images",
            field=models.URLField(verbose_name=400),
        ),
    ]
