# Generated by Django 4.1.6 on 2023-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0022_alter_recipelist_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipelist",
            name="images",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
