# Generated by Django 4.1.6 on 2023-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0025_alter_recipelist_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipelist",
            name="images",
            field=models.FileField(upload_to="food_planner/management/media/images"),
        ),
    ]
