# Generated by Django 4.1.6 on 2023-03-21 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_planner", "0027_alter_recipelist_images"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeList",
        ),
    ]
